project:
  type: website

website:
  #site-url: add domain once we have it
  #repo-url: I assume we will need to host it on github or similar
  #image: add logo image once we have it
  #favicon: add favicon once we have it
  title: "Community Conservation Award" #might not need this line
  open-graph: true #internet protocol that uses special meta tags in a webpage's HTML to control how a link looks when shared on social media and messaging apps
  
  twitter-card: true #a snippet of rich preview information that automatically appears when a website URL is shared in a post on X
  
  navbar:
    background: "#f1f1f1"
    search: false
    pinned: true
    collapse: false
    left:
      - href: about.qmd
        text: About Us
      - href: fundedprojects.qmd
        text: Previously Funded Projects
      - href: enquiries.qmd
        text: Enquiries
  
      
  
  page-footer: 
    background: "#f1f1f1"
    
    left: |
      2026 All rights reserved.
    center: |
      Website created by Science Graphic Design in Quarto. 
      
    right:
      - icon: bluesky
        href: https://bsky.app/profile/name
      - icon: instagram
        href: https://www.instagram.com/profilename
    
format:
  html:
    theme:
      - cosmo #not sure about this one
      - brand
    css: styles.css
    toc: true

editor: visual

